[project]
name = "projeto-analise-vendas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "sqlalchemy>=2.0.46",
]
