[project]
name = "projeto-analise-vendas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "kaleido>=1.2.0",
    "notebook>=7.5.3",
    "pandas>=3.0.0",
    "plotly>=6.5.2",
    "sqlalchemy>=2.0.46",
]
